#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
PLANS_DIR = REPO_ROOT / "agents/plans"
WORKFLOW_PROMPT_PATH = "agents/prompts/workflows/execplan.md"


def slugify(value: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9\s-]", "", value).strip().lower()
    normalized = re.sub(r"[\s_-]+", "-", normalized)
    normalized = re.sub(r"-+", "-", normalized)
    return normalized.strip("-")


def title_from_slug(slug: str) -> str:
    words = [part for part in slug.split("-") if part]
    if not words:
        return "New ExecPlan"
    return " ".join(word.capitalize() for word in words)


def build_scaffold(title: str) -> str:
    return (
        f"# {title}\n\n"
        "This ExecPlan is a living document. The sections `Progress`, `Surprises & Discoveries`, "
        "`Decision Log`, and `Outcomes & Retrospective` must be kept up to date as work proceeds.\n\n"
        f"This repository includes `{WORKFLOW_PROMPT_PATH}`. This document must be maintained "
        f"in accordance with `{WORKFLOW_PROMPT_PATH}`.\n\n"
        "## Purpose / Big Picture\n\n"
        "Describe the user-visible outcome and why it matters.\n\n"
        "## Progress\n\n"
        "- [ ] (<YYYY-MM-DD HH:MMZ>) Capture initial context and constraints.\n"
        "- [ ] (<YYYY-MM-DD HH:MMZ>) Implement planned changes.\n"
        "- [ ] (<YYYY-MM-DD HH:MMZ>) Run validation and collect evidence.\n"
        "- [ ] (<YYYY-MM-DD HH:MMZ>) Complete reflection and handoff notes.\n\n"
        "## Surprises & Discoveries\n\n"
        "- Observation: TBD\n"
        "  Evidence: TBD\n\n"
        "## Decision Log\n\n"
        "- Decision: TBD\n"
        "  Rationale: TBD\n"
        "  Date/Author: TBD\n\n"
        "## Outcomes & Retrospective\n\n"
        "Planned outcome: TBD\n\n"
        "Completion updates: TBD\n\n"
        "## Context and Orientation\n\n"
        "Describe relevant repository context, constraints, and terminology for a new contributor.\n\n"
        "## Plan of Work\n\n"
        "Describe the implementation approach in prose before listing command-level steps.\n\n"
        "## Concrete Steps\n\n"
        f"Run commands from `{REPO_ROOT}`.\n\n"
        "1. TBD\n\n"
        "    <command>\n\n"
        "Expected result: TBD\n\n"
        "## Validation and Acceptance\n\n"
        "Define observable acceptance criteria and exact validation commands with expected outcomes.\n\n"
        "If this task requires git closeout, include branch/commit/push/PR checks and record the PR URL.\n\n"
        "## Idempotence and Recovery\n\n"
        "Describe rerun safety, rollback strategy, and failure recovery paths.\n\n"
        "## Artifacts and Notes\n\n"
        "List expected artifacts and include links/paths to execution evidence.\n\n"
        "## Interfaces and Dependencies\n\n"
        "List touched interfaces, contracts, and dependencies (or state `None`).\n\n"
        "## Final Reflection Round\n\n"
        "### Outcome\n"
        "- TBD\n\n"
        "### What Changed\n"
        "- TBD\n\n"
        "### Key Decisions and Trade-offs\n"
        "- TBD\n\n"
        "### Lessons Learned\n"
        "- TBD\n\n"
        "### Memories to Promote\n"
        "- TBD\n\n"
        "### Frictions and Complaints\n"
        "- TBD\n\n"
        "### Improvement Proposals\n"
        "- TBD\n\n"
        "### Evidence\n"
        "- TBD\n\n"
        "### Next Steps\n"
        "- TBD\n\n"
        "Revision note: Initial scaffold generated by `agents/scripts/new_execplan.py` "
        f"to comply with `{WORKFLOW_PROMPT_PATH}`.\n"
    )


def write_atomic(path: Path, content: str) -> None:
    tmp_path: Path | None = None
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", delete=False, dir=path.parent, prefix=".tmp_execplan_"
    ) as tmp_file:
        tmp_file.write(content)
        tmp_path = Path(tmp_file.name)
    try:
        os.replace(tmp_path, path)
    finally:
        if tmp_path.exists():
            tmp_path.unlink(missing_ok=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create an ExecPlan scaffold under agents/plans/.")
    parser.add_argument("--title", help="Human-readable plan title.")
    parser.add_argument("--slug", help="Optional output slug override.")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing file.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    provided_title = (args.title or "").strip()
    provided_slug = (args.slug or "").strip()

    if not provided_title and not provided_slug:
        print("ERROR: provide --title or --slug", file=sys.stderr)
        return 1

    slug_source = provided_slug or provided_title
    slug = slugify(slug_source)
    if not slug:
        print("ERROR: could not derive a valid slug from input", file=sys.stderr)
        return 1

    title = provided_title or title_from_slug(slug)

    PLANS_DIR.mkdir(parents=True, exist_ok=True)
    output_path = PLANS_DIR / f"{slug}.md"

    if output_path.exists() and not args.force:
        print(
            f"ERROR: file already exists: agents/plans/{output_path.name} (use --force to overwrite)",
            file=sys.stderr,
        )
        return 1

    content = build_scaffold(title)
    try:
        write_atomic(output_path, content)
    except OSError as exc:
        print(f"ERROR: failed to write file: {exc}", file=sys.stderr)
        return 1

    print(f"Created: agents/plans/{output_path.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
